version: "3"
services:
  server:
    image: server
    container_name: server
    build: .
    depends_on:
      - "rabbitmq"
    ports:
      - "8080:8080"
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
networks:
  default:
    external:
      name: token